apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fftcg-production

resources:
- ../../base/
- resources/backup-db-cronjob.yaml

patchesStrategicMerge:
- patches/ing.yaml

configMapGenerator:
- envs:
  - files/config.env
  name: env-config
