version: '2'
services:
    node:
        container_name: fftcg-node
        build:
            dockerfile: ./docker/node/Dockerfile
            context: .
        command: ["npm", "run", "watch"]
        volumes:
            - .:/var/www
        ports:
            - "3000:3000"
        env_file: .env

    postgres:
        container_name: fftcg-postgres
        build:
            dockerfile: ./docker/postgres/Dockerfile
            context: .
        ports:
            - "5432:5432"
        env_file: .env
