
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: fftcg-api
spec:
  rules:
  - host: fcc-api.preprod.micriber.com
    http:
      paths:
      - backend:
          serviceName: fftcg-api
          servicePort: http
        path: /
  tls:
  - hosts:
    - fcc-api.preprod.micriber.com
    secretName: fcc-api-preprod-micriber-com-tls
