apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: fftcg-preprod

resources:
- ../../base/

patchesStrategicMerge:
- ing.yaml

configMapGenerator:
- envs:
  - files/config.env
  name: env-config
