name: Build'n'Push'n'Deploy docker dev image

on:
  push:
    branches:
      - develop

env:
  REGISTRY_URL: registry.micriber.com
  IMAGE_NAME: fftcg-hub-api-preprod

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: https://registry.micriber.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Set docker image variable
        id: set_docker_image
        run: echo "::set-output name=docker_image::${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ steps.package-version.outputs.current-version}}-${GITHUB_SHA}"
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/node/Dockerfile.prod
          tags: ${{ steps.set_docker_image.outputs.docker_image }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  deploy-k8s:
    runs-on: ubuntu-latest
    needs: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Set docker image variable
        id: set_docker_image
        run: echo "::set-output name=docker_image::${{ env.REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ steps.package-version.outputs.current-version}}-${GITHUB_SHA}"
      - name: Set docker image to manifest
        uses: stefanprodan/kube-tools@v1
        with:
          kubectl: 1.18.2
          kustomize: 4.1.3
          command: |
            echo "Set image to deploy"
            cd infra/k8s/overlays/preprod && kustomize edit set image fftcg-api=${{ steps.set_docker_image.outputs.docker_image }} && kustomize edit set image sql-migrations=${{ steps.set_docker_image.outputs.docker_image }}
      - name: Deploy
        uses: danielr1996/kubectl-action@1.0.0
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          args: apply -k infra/k8s/overlays/preprod
