name: Check version upgraded

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: kriasoft/check-version@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
