name: Check version has been upgraded

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Display version information
        run: |
          echo "Version has been changed: ${{ steps.check.outputs.changed }}"
          echo "Version type: ${{ steps.check.outputs.type }}"
          echo "Version number: ${{ steps.check.outputs.version }}"
          echo "Version changed commit: ${{ steps.check.outputs.commit }}"
      - name: Version not change fail
        if: steps.check.outputs.changed == 'false'
        run: /bin/false
