name: Build'n'Push docker image

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: get-npm-version
        id: package-version
        uses: martinbeentjes/npm-get-version-action@master
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: https://registry.micriber.com
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}
      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./docker/node/Dockerfile.prod
          tags: registry.pawndev.com/fftcg-api:${{ steps.package-version.outputs.current-version}}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
  # deploy-k8s:
  #   runs-on: ubuntu-latest
    
