name: Check version upgraded

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: pawndev/check-version@cb0e6b907c698bfde9741dc9fc4ccfd850e55510
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
