name: Check version has been upgraded

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check version changes
        uses: EndBug/version-check@v1
        id: check
      - name: Version not change fail
        if: steps.check.outputs.changed == 'false'
        run: /bin/false
