name: Run test suite

on:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: node:12.18-stretch
            env:
                DB_HOST: postgres
                POSTGRES_USER: user
                POSTGRES_PASSWORD: password
                POSTGRES_DB_TEST: fftcg-application-test
                MIN_APP_VERSION: 0.4.0
        services:
            postgres:
                image: postgres:11.4
                env:
                    POSTGRES_USER: user
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: fftcg-application-test
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Install
              run: "npm ci"
            - name: Typescript
              run: "npm run check"
            - name: Linter
              run: "npm run eslint"
            - name: Test
              run: "npm run test"
