name: Run test suite

on:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        container: node:12.18-stretch
        services:
            postgres:
                image: postgres:11.4
                env:
                    POSTGRES_USER: user
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: fftcg-application-test
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Set env
              run: "cp .env.dist .env"
            - name: Check typescript
              run: "npm run check"
            - name: Check linter
              run: "npm run eslint"
            - name: Load fixture
              run: "npm run fixture:test"
            - name: Run func test with coverage
              run: "npm run test:func:cov"
