name: Run test suite

on:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        container:
            image: node:12.18-stretch
            env:
                DB_HOST: postgres
                POSTGRES_USER: user
                POSTGRES_PASSWORD: password
                POSTGRES_DB_TEST: fftcg-application-test
        services:
            postgres:
                image: postgres:11.4
                env:
                    POSTGRES_USER: user
                    POSTGRES_PASSWORD: password
                    POSTGRES_DB: fftcg-application-test
        steps:
            - name: Check out code
              uses: actions/checkout@v2
            - name: Install dependencies
              run: "npm ci"
            - name: typescript
              run: "npm run check"
            - name: linter
              run: "npm run eslint"
            - name: Migration
              run: "npm run migration:run:test"
            - name: Fixture
              run: "npm run fixture:test"
            - name: Test with coverage
              run: "npm run test:func:cov"
