name: Run test suite

on:
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Set env
              run: "cp .env.dist .env"
            - name: Up docker
              run: "make up"
            - name: Check typescript
              run: "make check"
            - name: Check linter
              run: "make eslint"
            - name: Load fixture
              run: "make fixture-test"
            - name: Run func test
              run: "make test-func-cov"
#            - name: Run unit test
#              run: "make test-unit"
